name: "Spoolman Server"
description: "Latest stable version of Spoolman."
url: "https://github.com/donkie/spoolman"
slug: "spoolman"
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: application
webui: "[PROTO:option_name]://[HOST]:[PORT:8000]"
environment:
  "SPOOLMAN_DIR_DATA": "/data"
  "PUID": "0"
  "PGID": "0"
  "SPOOLMAN_DB_TYPE": "sqlite"
  "SPOOLMAN_AUTOMATIC_BACKUP": "false"
boot: auto
ports:
  8000/tcp: 8000
image: ghcr.io/donkie/spoolman
version: 0.16.1
ingress: true
ingress_port: 8000
